### ISSUE TITLE
printing out posts in wp_footer() on front page

### ISSUE THREAD

**Issue by columbian-chris** [timber/debug-bar-timber#15]
For some reason, the plugin started printing out what looks like the posts on the front page template of my theme, calling in wp_footer(). Anyone else experience this?

Running:
- Timber Debug Bar 0.3
- Timber Library 1.9.2
- PHP 7.2.15
- Wordpress 5.1

**Comment by bigmike7801** [comment]
Any update on this?

I'm having the same issue.

**Comment by manzwebdesigns** [comment]
It appears that this plugin is not being maintained anymore... not sure but wish it would be. 😖

**Comment by manzwebdesigns** [comment]
It looks like this one (https://github.com/xenobytezero/debug-bar-timber) has been updated later than this one... 👍

**Comment by jarednova** [comment]
thanks for the nudge @manzwebdesigns! It's true, I haven't really been paying enough attention to this repo. 

@xenobytezero would you consider PRing your changes back to us here? I'd love to get the Debug Bar current with PHP 7.x and other things it looks like you worked on

**Comment by manzwebdesigns** [comment]
Hey, @jarednova, glad to help!  If you are wanting any help maintaining this plugin, I have been wanting to learn more about doing that.

**Comment by jarednova** [comment]
cool, I'll send you an email w some info @manzwebdesigns !

**Comment by xenobytezero** [comment]
> thanks for the nudge @manzwebdesigns! It's true, I haven't really been paying enough attention to this repo.
> 
> @xenobytezero would you consider PRing your changes back to us here? I'd love to get the Debug Bar current with PHP 7.x and other things it looks like you worked on

Yea I can, might take a little bit though as my PR depends on a local version of Krumo too, as well as some other changes I forgot I had made. Will try and take a look this week.

**Comment by manzwebdesigns** [comment]
> Yea I can, might take a little bit though as my PR depends on a local version of Krumo too, as well as some other changes I forgot I had made. Will try and take a look this week.
Thanks, @xenobytezero, I didn't know if you were going to respond so I went ahead and created a PR from my fork of your repo.
If you want me to, I can cancel it.

**Comment by xenobytezero** [comment]
> > Yea I can, might take a little bit though as my PR depends on a local version of Krumo too, as well as some other changes I forgot I had made. Will try and take a look this week.
> 
> Thanks, @xenobytezero, I didn't know if you were going to respond so I went ahead and created a PR from my fork of your repo.
> If you want me to, I can cancel it.

If you make it work before I get a chance to look at it, then go ahead.

**Comment by manzwebdesigns** [comment]
Sounds good.

**Comment by xenobytezero** [comment]
#17 PR created, moved back to the official distribution of Krumo, tested with WP 5.4.2 and PHP 7.3.18

**Comment by manzwebdesigns** [comment]
Awesome, thanks so much!
On 7/2/2020 7:51:42 PM, xenobytezero <notifications@github.com> wrote:
#17 [https://github.com/timber/debug-bar-timber/pull/17] PR created, moved back to the official distribution of Krumo, tested with WP 5.4.2 and PHP 7.3.18

**Comment by manzwebdesigns** [comment]
I have tested the PR with PHP 7.4.7 and it appears to work, but the layout for the information Krumo gives doesn't seem very easy to use.
