### ISSUE TITLE
Entire Debug Bar not showing on Frontend

### ISSUE THREAD

**Issue by landwire** [timber/debug-bar-timber#23]
Hi there,
I have the latest version of Wordpress, debug bar and timber debug bar installed.
The debug bar shows fine in the backend, with the timber option. But in the frontend of the site, the debug bar is not showing at all if I have timber debug bar installed. I have Timber 1.18.1 installed.

In my debug.log are no errors thrown afaics.

Anybody has similar problems?

**Comment by landwire** [comment]
Ok, it's in the html. Looks like a CSS styling issue. I have a look.

**Comment by landwire** [comment]
Ok, the problem comes from this rule from timber-debug-bar.scss
#wpadminbar .ab-top-secondary {
    top: -33px;
}

**Comment by manzwebdesigns** [comment]
First, thanks for using the toolbar!  We appreciate it.  I will fix that and get a new version up today.

**Comment by manzwebdesigns** [comment]
PR merged and new version released.  Thanks for that!

**Comment by jarednova** [comment]
Excellent, thanks @landwire and @manzwebdesigns for the info and the quick fix!!!

**Comment by landwire** [comment]
You are welcome. Is there still the old version on wpackagist? When I download over wordpress, I can see the changes. But via composer after deleting etc. the CSS was still there.

Maybe it helps to bump the version to 1.0.6?

**Comment by jarednova** [comment]
@landwire hmmmm, strange. The upload script we have to wp.org is supposed to keep that in sync as well. @manzwebdesigns could you take a look at that?

**Comment by manzwebdesigns** [comment]
Yeah, I will look at it later today.

**Comment by blendjasper** [comment]
@manzwebdesigns Could you have a look? https://wordpress.org/plugins/debug-bar-timber/ lists version 1.0.5

**Comment by manzwebdesigns** [comment]
Hi @blendjasper, I am not sure what is going on.  I just created a new release, 1.0.7, and pushed it to the WP plugins but it still reflects 1.0.5 there.

**Comment by jasperkooij** [comment]
<img width="307" alt="Screen Shot 2020-10-28 at 20 58 47" src="https://user-images.githubusercontent.com/18720/97516156-85f65400-1960-11eb-8643-24c6534b19d1.png">
@manzwebdesigns I've deleted and reinstalled the plugin and it is back on the admin bar. It is the right code but listed as "Version 1.0.5".

Does https://github.com/timber/debug-bar-timber/blob/master/debug-bar-timber.php need a version number update?

**Comment by manzwebdesigns** [comment]
Wow, what a n00b mistake!  It now reflects the correct version.

**Comment by jasperkooij** [comment]
@manzwebdesigns Glad, I could help. I use this toolbar all the time!

**Comment by manzwebdesigns** [comment]
@jasperkooij Thanks for using it.  Please feel free to contact me if you would like to see new features added.  We are very interested in building this out to be as useful as possible!
