### ISSUE TITLE
Version Numbering discrepancies

### ISSUE THREAD

**Issue by jarednova** [timber/debug-bar-timber#29]
It looks like version numbers between GitHub and WordPress.org are getting scrambled. The most recent release (that @manzwebdesigns deployed the other day) from GitHub is 1.1.5:

https://github.com/timber/debug-bar-timber/releases/tag/1.1.5

... but according to WordPress.org it's 1.0.5:

![Screen Shot 2021-09-23 at 4 51 10 PM](https://user-images.githubusercontent.com/1298086/134582112-dddb838f-27c2-4309-a893-0d27944c1aa3.png)

https://wordpress.org/plugins/debug-bar-timber/

... to make matters even more fun, the `readme.txt` reports `1.0.10`. There might be a mix of manual and script work here. Just wanted to call it out as an issue as it might be related to https://github.com/timber/timber/issues/2477

**Comment by manzwebdesigns** [comment]
Okay, so help me out... how do I fix this?  Just update the readme.txt file?

**Comment by jarednova** [comment]
Yep! looks like it might have to be updated in two different files/places:

https://github.com/timber/debug-bar-timber/blob/master/debug-bar-timber.php#L7
https://github.com/timber/debug-bar-timber/blob/master/readme.txt#L6

**Comment by manzwebdesigns** [comment]
All good now!  So I need to remember to update the version numbers on thos files going forward!

**Comment by jarednova** [comment]
Yeah, I wish there was some way to automate. But I find I have to do a manual process with "main" Timber as well!
