### ISSUE TITLE
Timber + Debug Bar - Theme crash

### ISSUE THREAD

**Issue by katipierson** [timber/debug-bar-timber#30]
Hello,

my Theme crashs at any page, if i use the latest Version from Timber with the latest? Timber Debug-Bar. If i disable the Debug-Bar the Theme is alright.

## Expected behavior
The "Screen" is wrong. The theme does not have the full width on the desktop, just maybe tablet size. The error is also with the timber-starter-theme.

## Actual behavior
I see an Error in Debug-Bar under Timber:
`Fatal error: Method Timber\FunctionWrapper::__toString() must not throw an exception, caught Error: Call to undefined function Symfony\Component\VarDumper\Caster\str_contains() in /wp-content/plugins/timber-library/vendor/twig/twig/src/Environment.php(497) : eval()'d code on line 0`
There is no other output.

## What version of WordPress, PHP and Timber are you using?
Wordpress: 5.8 / Timber: 1.18.2 / Timber-Debug-Bar: 1.0.8 (i tried 1.1.4 from your github here. However, it also appears to me as 1.0.8) / ACF 5.9.9 (if I deactivate it nothing changes) - no more plugins

PHP 7.3.22 - as fpm

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Github & Wordpress-Plugin-Directory

**Comment by jarednova** [comment]
Thanks @katipierson! I transferred the issue to the Debug Bar repo so we could do a deeper dive. Given that the error is in AltoRouter, I think that's an interesting place to start. Are you using custom routing features? Can you help us isolate whether disabling portions of your theme code suppress or trigger the error

**Comment by katipierson** [comment]
Thanks @jarednova. The theme is basically brand new without any things. Really just an index.twig, index.php and functions.php + bootstrap. No routes.

**Comment by manzwebdesigns** [comment]
Hi @katipierson, My apologies for the delay in responding.  Are you still having this issue?

**Comment by katipierson** [comment]
@manzwebdesigns Yes, the problem persists.

**Comment by manzwebdesigns** [comment]
@katipierson Please try the latest version (1.1.8) and confirm that the issue still exists.

**Comment by katipierson** [comment]
@manzwebdesigns  

The installation was not possible via Composer and wpackagist.org and via wordpress.org. The old version 1.1.6 is still there.

I used the release version here from GitHub.

I had to change the PHP version to 7.4.28. It doesn't work at all with PHP version 7.3.22.
The reason was lines 14 to 17 in the class-debug-bar-timber.php file. "public array" is only used since PHP version 7.4. supports.

Timber 1.19.1
Debug Bar 1.1.2
Timber Debug Bar V1.1.8

And now it works. Great Job.

You might be interested in a few notices that have appeared:
```
{# expected variables:
Notice: Undefined offset: 0 in /var/www/html/zeraruna/htdocs/wp-content/plugins/debug-bar-timber/class-debug-bar-timber.php on line 133
layout: array of the form array[0][X] where X is

Notice: Undefined offset: 0 in /var/www/html/zeraruna/htdocs/wp-content/plugins/debug-bar-timber/class-debug-bar-timber.php on line 133
menus: array of the form array[0][X] where X is
#}
```
