### ISSUE TITLE
PHP fatal error under WP 3.9.2

### ISSUE THREAD

**Issue by plweil** [timber/debug-bar-timber#6]
Using the latest commit of Timber Debug Bar, I'm getting this error when I try to load a page under WP 3.9.2, with Timber Debug bar and Debug Bar activated:

PHP Fatal error:  Using $this when not in object context in /var/www/public/content/plugins/debug-bar-timber/class-debug-bar-timber.php on line 19

Reverting to commit #39fac03 eliminates the problem.

**Comment by manzwebdesigns** [comment]
Outdated issue and not existant in current version.  Please repost if needed.
